project:
  type: book
  output-dir: docs

book:
  title: "FluvialGeomorph Technical Manual"
 # author:
 #   - Christopher Haring, Geomorphologist/Research Physical Scientist, Coastal Hydraulics Laboratory, U.S. Army Corps of Engineers
 #   - Michael Dougherty, Geographer, US Army Corps of Engineers, Rock Island District
  date: "2026-06-10"
  repo-url: https://github.com/FluvialGeomorph/FG-Tech-Manual
  page-navigation: true
  search: true

  chapters:
    - index.qmd
    - Intro.qmd
    - part: "Foundations"
      chapters:
        - quickguide.qmd
        - concepts.qmd
        - flowchart.qmd
        - concept_map.qmd
        - Metrics.qmd
        - FieldMethods.qmd
    - part: "FluvialGeomorph Toolbox"
      chapters:
        - Install.qmd
        - TutorialData.qmd
        - Toolbox.qmd
        - Features.qmd
        - Reports.qmd
        - Level-1.qmd
        - Level-2-eb.qmd
        - Level-2.qmd
        - Level-3.qmd
        - FromField.qmd
        - Validation.qmd
    - part: "Rapid Assessment Tools"
      chapters:
        - floodplain.qmd
        - ohwm.qmd
        - chute.qmd
    - part: "R Packages"
      chapters:
        - regionalcurve.qmd
        - fluvgeo.qmd


    - References.qmd
    - Glossary.qmd

  appendices:
    - QA-checklist.qmd
    - DB-migration.qmd
    - codediagram.qmd


  sidebar:
    style: "docked"
    background: light
  page-footer:
    left: "Made with love by USACE"
    background: light

bibliography: [packages.bib, book.bib]
number-depth: 1


format:
  html:
    mermaid:
      theme: default
    theme:
      light: flatly
      dark: darkly
    filters:
      - quarto
      - fontawesome
    respect-user-color-scheme: true
    css: [styles.css, custom.css]
editor: source
