project:
  type: book
  output-dir: docs

book:
  title: "FluvialGeomorph Technical Manual"
  author:
    - Christopher Haring, Geomorphologist/Research Physical Scientist, Coastal Hydraulics Laboratory, U.S. Army Corps of Engineers
    - Michael Dougherty, Geographer, US Army Corps of Engineers, Rock Island District
  date: "2025-06-02"
  repo-url: https://github.com/FluvialGeomorph/FG-Tech-Manual
  page-navigation: true
  search: true

  chapters:
    - index.qmd
    - 0-1-Intro.qmd
    - part: "Foundations"
      chapters:
        - 1-1-Concepts.qmd
        - 1-2-Metrics.qmd
        - 1-3-FieldMethods.qmd
    - part: "Tools"
      chapters:
        - 2-1-Install.qmd
        - 2-2-TutorialData.qmd
        - 2-3-Toolbox.qmd
        - 2-4-Features.qmd
        - 2-5-Reports.qmd
    - part: "Workflows"
      chapters:
        - 3-1-Workflows.qmd
        - 3-2-CreateTerrain.qmd
        - 3-3-Level-1.qmd
        - 3-4-Level-2.qmd
        - 3-5-Level-3.qmd
    - 0-7-References.qmd
  appendices:
    - 4-1-QAChecklist.qmd

  sidebar:
    style: docked
    background: light
  page-footer:
    left: "Made with love by USACE"
    background: light

bibliography: [packages.bib, book.bib]
number-depth: 1

format:
  html:
    light: flatly
    dark: darkly

editor: source
